# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

config.set('qt.highdpi', True)
# config.set('fonts.completion.category', 'bold 24pt monospace')
# config.set('fonts.completion.entry', '24pt monospace')
# config.set('fonts.debug_console', '24pt monospace')
# config.set('fonts.downloads', '24pt monospace')
# config.set('fonts.hints', '24pt monospace')
# config.set('fonts.keyhint', '24pt monospace')
# config.set('fonts.messages.error', '24pt monospace')
# config.set('fonts.messages.info', '24pt monospace')
# config.set('fonts.messages.warning', '24pt monospace')
# config.set('fonts.prompts', '24pt monospace')
# config.set('fonts.statusbar', '24pt monospace')
# config.set('fonts.tabs', '24pt monospace')
# config.set('zoom.default', '90%')
config.set('fonts.completion.category', 'bold 8pt monospace')
config.set('fonts.completion.entry', '8pt monospace')
config.set('fonts.debug_console', '8pt monospace')
config.set('fonts.downloads', '8pt monospace')
config.set('fonts.hints', '8pt monospace')
config.set('fonts.keyhint', '8pt monospace')
config.set('fonts.messages.error', '8pt monospace')
config.set('fonts.messages.info', '8pt monospace')
config.set('fonts.messages.warning', '8pt monospace')
config.set('fonts.prompts', '8pt monospace')
config.set('fonts.statusbar', '8pt monospace')
config.set('fonts.tabs', '8pt monospace')
config.set('zoom.default', '125%')

# config.bind('J', 'tab-prev')
# config.bind('K', 'tab-next')
