#!/bin/sh

monitor_setup.sh

environment_vars="DBUS_SESSION_BUS_ADDRESS DISPLAY SSH_AUTH_SOCK"
environment_vars="$environment_vars XAUTHORITY XDG_DATA_DIRS XDG_RUNTIME_DIR XDG_SESSION_ID"
environment_vars="$environment_vars PASSWORD_STORE_DIR WINIT_X11_SCALE_FACTOR GNUPGHOME"
environment_vars="$environment_vars FONTCONFIG_PATH FONTCONFIG_FILE"
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment $environment_vars
dbus-update-activation-environment $environment_vars

systemctl --user --no-block start cellar-xsession.target

display_adj.sh = &
touchpad_setup.sh &
touchscreen_setup.sh &
setxkbmap -option caps:ctrl_modifier -layout us,us,cz -variant ,colemak,qwerty

brave &
# wait for emacs in a subshell
(systemctl --user start emacs && emacsclient -c) &
xss-lock slock &

exec bspwm
