#! /usr/bin/fish

set metadata (sp metadata)
set sp_status (sp status)

if test -z $metadata || test $sp_status = Stopped
	exit
end

set title (string escape $metadata | rg -e "\btitle\b" | cut -d"|" -f2 | string trim -c"''")
set author (string escape $metadata| rg -e "\bartist\b" | cut -d"|" -f2 | string trim -c "'")

# if test (string length $title) -gt 25
# 	set short_title (string sub -l 22 $title)"..."
# else
# 	set short_title $title
# end

# if test (string length $author) -gt 20
# 	set short_author (string sub -l 17 $author)"..."
# else
# 	set short_author $author
# end
#

switch $sp_status
	case Playing
		set stat_icon "||"
	case Paused
		set stat_icon "|>"
	case "*"
		set stat_icon "??"
end

set short_title $title
set short_author $author

echo $short_title" ["$short_author"] "$stat_icon
echo $title" ["$author"] "$stat_icon
